version: '3.7'

services:
  mariadb:
    image: 'mariadb:11.3.2'
    restart: always
    environment:
      MARIADB_DATABASE: warhammer
      MARIADB_USER: inigo
      MARIADB_PASSWORD: sasa1234
      MARIADB_ROOT_PASSWORD: sasa1234
    ports:
      - 3307:3306
    networks:
      - warhammer-net
    
networks:
  warhammer-net:
